version: "3.7"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234



# exec into shell
# docker exec -it gofiberrestful_db_1 psql -U user -h 127.0.0.1 -p 5432
